### ISSUE TITLE
Allow request mutation based on Access decision

### ISSUE THREAD

**Issue by vivekmittal07** [google/fhir-gateway#122]
Parent bug - https://github.com/google/fhir-gateway/issues/108

ONA enabled preprocessing of request for an access decision - https://github.com/opensrp/fhir-access-proxy/commit/09584ef2bb5682bc3c9280ec1b72ad3432918019.

We wanted to support Query rewrite option in the design doc - https://github.com/google/fhir-gateway/blob/main/doc/design.md

**Comment by vivekmittal07** [comment]
This is not straight forward task as the AccessChecker design explicitly prevents request mutation.

**Comment by bashir2** [comment]
So yeah, we explicitly prevent mutating the input request by the access-checker plugin because otherwise it would be hard to reason about the query in the server code. Looking at ONA's use-case, it seems that the issues of access-control and implementing a sync-strategy are mixed together into an access-checker. That is probably the bigger question to answer whether we want to support that pattern or not; because I think sync-strategy is a separate concern.

To answer what to do for this issue, here are some options after talking with @vivekmittal07  (in the order of my personal preference):
- Encourage ONA to separate the sync-strategy and move it to the client as discussed above (so access-checker plugin does access-control only).
- Add an interface for mutating the FHIR query but only allow adding URL parameters (this is mostly for read/search queries and can be applied to both URLs and POST body content when doing search by POST). This is what we wanted to support in the original design doc too.
- Send the raw query to the access-checker and let it change however it wants.

**Comment by jjtswan** [comment]
@vivekmittal07 Any thoughts on the approaches above?  Do we think that Bashir's first option will work in their currently designed architecture?

**Comment by jjtswan** [comment]
Can we clear this up quickly?  Changing out client-APIs can be done, but gets harder once something is deployed and gets more rolled out.

**Comment by vivekmittal07** [comment]
We decided to proceed with 2nd option mentioned in https://github.com/google/fhir-gateway/issues/122#issuecomment-1485665294

Supporting custom endpoints is not straightforward and it will be good to see how we can support this. This is outside the scope of the bug. I will create a new feature request for this.

**Comment by jjtswan** [comment]
This bug was closed, but I cannot tell if we decided to drop it, or if it was resolved?  If the latter, can you associate the PR?

**Comment by vivekmittal07** [comment]
The changes are already merged and the PR is attached above - https://github.com/google/fhir-gateway/pull/140
