### ISSUE TITLE
Release new image for FHIR Gateway

### ISSUE THREAD

**Issue by jjtswan** [google/fhir-gateway#123]
While running through the [fhir-app-examples instructions](https://github.com/google/fhir-app-examples/blob/main/README.md), William and I noticed that the instructions make references to the following docker images:

`us-docker.pkg.dev/fhir-proxy-build/stable/fhir-access-proxy:latest`

Two things here.

1. We shoudl probably update the naming to be FHIR-gateway.
2. When we checked this image, it looks like it was last built / released in mid-2022.
3. Upon fixing the name / path, we should go back and also adjust the instructions back at the link at the top.

**Comment by jjtswan** [comment]
I remember that @vivekmittal07 did a recent release for the fhir access proxy.  Wondering if this got addressed.  No worries if not.

**Comment by vivekmittal07** [comment]
Thanks Justin for flagging this. The image is automatically pushed by kokoro but we have to tag that manually.

@bashir2 I noticed that kokoro also pushes a new image on presubmit of a PR. 
Should we remove this and only allow continuous build to push to kokoro ?   

We will update the release document to avoid this in future.

**Comment by bashir2** [comment]
Pushing a new image per each continuous-build run is intentional ([here](https://github.com/google/fhir-gateway/blob/95dd4f64a05a4123f3230445f2414e4d9d620b20/build.sh#L31)) and the idea is to be able to quickly check/debug the image that failed a build. The tag is the `KOKORO_BUILD_ID` which can be grabbed from the PR page.

We can probably set up a purge policy to delete very old images but we should keep creating new images per CB run (I just manually deleted images from last year).

We still need a new image based on the [v0.2.0 release](https://github.com/google/fhir-gateway/releases/tag/0.2.0) which I am going to create soon.

**Comment by bashir2** [comment]
Just pushed a [new image](https://pantheon.corp.google.com/artifacts/docker/fhir-proxy-build/us/stable/fhir-access-proxy/sha256:3b3f8ea6e3ebe3dfeff2ddce2099876aa11bd4395bfc2d5f43ffbf97e6fa2574?project=fhir-proxy-build) and tagged it with both `v0.2.0` and `latest`. @williamito @jjtswan @anchita-g if anyone of you can test this is the context of   `fhir-app-examples` repo, it would be great.
